---
- name: Install Apache Web Server and upload my Web Page
  hosts: all
  become: yes

  vars:
  - source_file: ./MyWebSite/index.html
  - destin_file: /var/www/html

  tasks:
  - name: Install Apache WebServer
    yum: name=httpd state=latest

  - name: Copy MyHomePage to Servers
    copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Apache and Enable it on the every boot
    service: name=httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted